server:
  port: 10768
spring:
  application:
    name: Jetbrains-Help
  thymeleaf:
    cache: false
sa-token:
  active-timeout: 86400
  is-concurrent: true
  is-share: false
  token-style: tik
  is-log: true
logging:
  file:
    path: logs/${spring.application.name}
  level:
    root: error
    com.jetbrains.help: debug
help:
  product-id: dbeaver-ue
  product-version: 24.0
  default-email: Yamato@Azuelane.com
  default-license-name: Azuelane
  default-assignee-name: Yamato
  default-expiry-date: 2030-12-31
auth:
  enable: false
  type: linuxDo
  config:
    clientId: 123
    clientSecret: 321
    redirectUri: http://127.0.0.1:20768/auth/callback