spring:
  application:
    name: Jetbrains-Help
  thymeleaf:
    cache: false
  security:
    user:
      name: admin
      password: admin
server:
  port: 10768
help:
  enable-security: false
  product-id: dbeaver-ue
  product-version: 24.0
  default-email: Yamato@Azuelane.com
  default-license-name: Azuelane
  default-assignee-name: Yamato
  default-expiry-date: 2030-12-31
