spring:
  application:
    name: Jetbrains-Help
  thymeleaf:
    cache: false
server:
  port: 10768
help:
  product-id: dbeaver-ue
  product-version: 24.0
  default-email: Yamato@Azuelane.com
  default-license-name: Azuelane
  default-assignee-name: Yamato
  default-expiry-date: 2030-12-31
