server:
  port: 20768
spring:
  application:
    name: Jetbrains-Help
  thymeleaf:
    cache: false
sa-token:
  active-timeout: 86400
  is-concurrent: true
  is-share: false
  token-style: tik
  is-log: true
help:
  enable-auth: false
  auth-code: 123
  product-id: dbeaver-ue
  product-version: 24.0
  default-email: Yamato@Azuelane.com
  default-license-name: Azuelane
  default-assignee-name: Yamato
  default-expiry-date: 2030-12-31
